### ISSUE TITLE
Trouble implementing image helper

### ISSUE THREAD

**Issue by JTGA** [JTGA/cheerups#4]
What User story am I working on?

As a user I would like to be able to upload an image.

What error am I getting?

I am unable to incorporate an image tag correctly in my code.

What have I already attempted to fix the error?

I have tried googling the problem and reading 
http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html

**Comment by ghost** [comment]
@JTGA haha I've been looking under @h4w5 for new issues, man!

If you are trying to add images with a uri, you just add that uri to the DB and then use the `image_tag` helper.

Otherwise, if you want to implement Paperclip, check out the docs (https://github.com/thoughtbot/paperclip) and talk to Jason and Tara (et al).
